config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  get 'home/index'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'


  resource :contacts, only: [:new, :create], path_names: { :new => '' }
  resources :articles do
    resources :comments
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :massage, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!

  def index
    @articles = Article.all
  end
  
  def show
    @article = Article.find (params[:id])
  end

  def new
  end

  def create
  	@article = Article.new(article_params)
    if @article.save
       redirect_to @article
    else
      render action: 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
       redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end  

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)

    redirect_to articles_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :massage)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def terms 
  end 

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>
	<p>
	  <%= f.label :title %><br />
	  <%= f.text_field :title %>
	</p>

	<p>
	  <%= f.label :text %><br />
	  <%= f.text_area :text %>
	</p>

	<p>
	  <%= f.submit %>
	</p>

<% end %>

app/views/articles/index.html.erb
<h1>List of article</h1>

<% @articles.each do |article| %>
  
  <h2><%= article.title %></h2>

  <p><%= article.text %></p>

  <p>
    <%= link_to 'Show all articles!', article_path(article) %> |
    <%= link_to 'Edit', edit_article_path(article) %> |
    <%=  link_to 'Delete', article_path(article), data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?' }%>

  </p>

  <hr />

<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= form_for :article, url: articles_path, data: {turbo:false} do |f| %>
	<p>
	  <%= f.label :title %><br />
	  <%= f.text_field :title %>
	</p>

	<p>
	  <%= f.label :text %><br />
	  <%= f.text_area :text %>
	</p>

	<p>
	  <%= f.submit %>
	</p>

<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
    <%= @article.text %>
</p>

<h2>Comments</h2>

<% @article.comments.each do |comment| %>
<p>
  <i><%= comment.author %> said:</i><br />
  <%= comment.body %>
</p>
<% end %>

<h2>Add comment</h2>

<%= form_for([@article, @article.comments.build]) do |f| %>
    
    <p>
      <%= f.label :author %><br />
      <%= f.text_field :author %>
    </p>

    <p>
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %>
    </p>


<% end %>

app/views/contacts/create.html.erb
<p>
  Thancks!
</p>

app/views/contacts/new.html.erb
<h1>Contact us</h1>

<%= form_for :contact, url: contacts_path, data: {turbo:false} do |f| %>

  <% if @contact && @contact.errors.any? %>

  <p>
    <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </p>
  <% end %>

  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :massage %><br /> <!--#изменить букву-->
    <%= f.text_area :massage %>
  </p>

  <p>
    <%= f.submit 'Send message' %>
  </p>

<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" type="text/css" href="https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About as</h1>

app/views/pages/terms.html.erb
<h1>Terms of service</h1>